export const VehicleImages = {
    1: [
        require('../assets/vehicles/motorcycle/motorcycle_1/motorcycle_1_stitch.png'),
        require('../assets/vehicles/motorcycle/motorcycle_2/motorcycle_2_stitch.png'),
        require('../assets/vehicles/motorcycle/motorcycle_3/motorcycle_3_stitch.png'),
        require('../assets/vehicles/motorcycle/motorcycle_4/motorcycle_4_stitch.png'),
        require('../assets/vehicles/motorcycle/motorcycle_5/motorcycle_5_stitch.png'),
        require('../assets/vehicles/motorcycle/motorcycle_6/motorcycle_6_stitch.png'),
        require('../assets/vehicles/motorcycle/motorcycle_7/motorcycle_7_stitch.png'),
        require('../assets/vehicles/motorcycle/motorcycle_8/motorcycle_8_stitch.png'),
    ],
    2: [
        require('../assets/vehicles/motor_scooter/motor_scooter_1/motor_scooter_1_stitch.png'),
        require('../assets/vehicles/motor_scooter/motor_scooter_2/motor_scooter_2_stitch.png'),
    ],
    3: [
        require('../assets/vehicles/motor_car/motor_car_1/motor_car_1_stitch.png'),
        require('../assets/vehicles/motor_car/motor_car_2/motor_car_2_stitch.png'),
        require('../assets/vehicles/motor_car/motor_car_3/motor_car_3_stitch.png'),
        require('../assets/vehicles/motor_car/motor_car_4/motor_car_4_stitch.png'),
        require('../assets/vehicles/motor_car/motor_car_5/motor_car_5_stitch.png'),
    ],
    6: [
        require('../assets/vehicles/motor_van/motor_van_1/motor_van_1_stitch.png'),
        require('../assets/vehicles/motor_van/motor_van_2/motor_van_2_stitch.png'),
        require('../assets/vehicles/motor_van/motor_van_3/motor_van_3_stitch.png'),
        require('../assets/vehicles/motor_van/motor_van_4/motor_van_4_stitch.png'),
        require('../assets/vehicles/motor_van/motor_van_5/motor_van_5_stitch.png'),
    ],
    8: [
        require('../assets/vehicles/bus/bus_1/bus_1_stitch.png'),
        require('../assets/vehicles/bus/bus_2/bus_2_stitch.png'),
    ],
    9: [
        require('../assets/vehicles/bicycle/bicycle_1/bicycle_1_stitch.png'),
        require('../assets/vehicles/bicycle/bicycle_2/bicycle_2_stitch.png'),
        require('../assets/vehicles/bicycle/bicycle_3/bicycle_3_stitch.png')
    ],
    11: [
        require('../assets/vehicles/tricycle/tricycle_stitch.png'),
    ],
    13: [
        require('../assets/vehicles/lorry/lorry_1/lorry_1_stitch.png'),
        require('../assets/vehicles/lorry/lorry_2/lorry_2_stitch.png'),
    ],
    14: [
        require('../assets/vehicles/pick-up/pick-up_1/pick-up_1_stitch.png'),
        require('../assets/vehicles/pick-up/pick-up_2/pick-up_2_stitch.png'),
    ],
    15: [
        require('../assets/vehicles/prime_mover/prime_mover_stitch.png'),
    ],
    17: [
        require('../assets/vehicles/tipper_truck/tipper_truck_stitch.png'),
    ],
    18: [
        require('../assets/vehicles/tanker/tanker_stitch.png'),
    ],
    19: [
        require('../assets/vehicles/electric_scooter/electric_scooter_1/electric_scooter_1_stitch.png'),
        require('../assets/vehicles/electric_scooter/electric_scooter_2/electric_scooter_2_stitch.png'),
    ],
};

export const VehicleViews = {
    '1_1': {
        'front': require('../assets/vehicles/motorcycle/motorcycle_1/motorcycle_1_front.png'),
        'left': require('../assets/vehicles/motorcycle/motorcycle_1/motorcycle_1_left.png'),
        'right': require('../assets/vehicles/motorcycle/motorcycle_1/motorcycle_1_right.png'),
        'rear': require('../assets/vehicles/motorcycle/motorcycle_1/motorcycle_1_rear.png'),
        'top': require('../assets/vehicles/motorcycle/motorcycle_1/motorcycle_1_top.png'),
        'box': require('../assets/vehicles/motorcycle/motorcycle_1/motorcycle_1_box.png'),
    },
    '1_2': {
        'front': require('../assets/vehicles/motorcycle/motorcycle_2/motorcycle_2_front.png'),
        'left': require('../assets/vehicles/motorcycle/motorcycle_2/motorcycle_2_left.png'),
        'right': require('../assets/vehicles/motorcycle/motorcycle_2/motorcycle_2_right.png'),
        'rear': require('../assets/vehicles/motorcycle/motorcycle_2/motorcycle_2_rear.png'),
        'top': require('../assets/vehicles/motorcycle/motorcycle_2/motorcycle_2_top.png'),
        'box': require('../assets/vehicles/motorcycle/motorcycle_2/motorcycle_2_box.png'),
    },
    '1_3': {
        'front': require('../assets/vehicles/motorcycle/motorcycle_3/motorcycle_3_front.png'),
        'left': require('../assets/vehicles/motorcycle/motorcycle_3/motorcycle_3_left.png'),
        'right': require('../assets/vehicles/motorcycle/motorcycle_3/motorcycle_3_right.png'),
        'rear': require('../assets/vehicles/motorcycle/motorcycle_3/motorcycle_3_rear.png'),
        'top': require('../assets/vehicles/motorcycle/motorcycle_3/motorcycle_3_top.png'),
        'box': require('../assets/vehicles/motorcycle/motorcycle_3/motorcycle_3_box.png'),
    },
    '1_4': {
        'front': require('../assets/vehicles/motorcycle/motorcycle_4/motorcycle_4_front.png'),
        'left': require('../assets/vehicles/motorcycle/motorcycle_4/motorcycle_4_left.png'),
        'right': require('../assets/vehicles/motorcycle/motorcycle_4/motorcycle_4_right.png'),
        'top': require('../assets/vehicles/motorcycle/motorcycle_4/motorcycle_4_top.png'),
        'box': require('../assets/vehicles/motorcycle/motorcycle_4/motorcycle_4_box.png'),
    },
    '1_5': {
        'front': require('../assets/vehicles/motorcycle/motorcycle_5/motorcycle_5_front.png'),
        'left': require('../assets/vehicles/motorcycle/motorcycle_5/motorcycle_5_left.png'),
        'right': require('../assets/vehicles/motorcycle/motorcycle_5/motorcycle_5_right.png'),
        'top': require('../assets/vehicles/motorcycle/motorcycle_5/motorcycle_5_top.png'),
        'box': require('../assets/vehicles/motorcycle/motorcycle_5/motorcycle_5_box.png'),
    },
    '1_6': {
        'front': require('../assets/vehicles/motorcycle/motorcycle_6/motorcycle_6_front.png'),
        'left': require('../assets/vehicles/motorcycle/motorcycle_6/motorcycle_6_left.png'),
        'right': require('../assets/vehicles/motorcycle/motorcycle_6/motorcycle_6_right.png'),
        'top': require('../assets/vehicles/motorcycle/motorcycle_6/motorcycle_6_top.png'),
        'box': require('../assets/vehicles/motorcycle/motorcycle_6/motorcycle_6_box.png'),
    },
    '1_7': {
        'front': require('../assets/vehicles/motorcycle/motorcycle_7/motorcycle_7_front.png'),
        'left': require('../assets/vehicles/motorcycle/motorcycle_7/motorcycle_7_left.png'),
        'right': require('../assets/vehicles/motorcycle/motorcycle_7/motorcycle_7_right.png'),
        'rear': require('../assets/vehicles/motorcycle/motorcycle_7/motorcycle_7_rear.png'),
        'top': require('../assets/vehicles/motorcycle/motorcycle_7/motorcycle_7_top.png'),
        'box': require('../assets/vehicles/motorcycle/motorcycle_7/motorcycle_7_box.png'),
    },
    '1_8': {
        'front': require('../assets/vehicles/motorcycle/motorcycle_8/motorcycle_8_front.png'),
        'left': require('../assets/vehicles/motorcycle/motorcycle_8/motorcycle_8_left.png'),
        'right': require('../assets/vehicles/motorcycle/motorcycle_8/motorcycle_8_right.png'),
        'top': require('../assets/vehicles/motorcycle/motorcycle_8/motorcycle_8_top.png'),
        'box': require('../assets/vehicles/motorcycle/motorcycle_8/motorcycle_8_box.png'),
    },
    '2_1': {
        'left': require('../assets/vehicles/motor_scooter/motor_scooter_1/motor_scooter_1_left.png'),
        'right': require('../assets/vehicles/motor_scooter/motor_scooter_1/motor_scooter_1_right.png'),
        'rear': require('../assets/vehicles/motor_scooter/motor_scooter_1/motor_scooter_1_rear.png'),
        'box': require('../assets/vehicles/motor_scooter/motor_scooter_1/motor_scooter_1_box.png'),
    },
    '2_2': {
        'left': require('../assets/vehicles/motor_scooter/motor_scooter_2/motor_scooter_2_left.png'),
        'right': require('../assets/vehicles/motor_scooter/motor_scooter_2/motor_scooter_2_right.png'),
        'rear': require('../assets/vehicles/motor_scooter/motor_scooter_2/motor_scooter_2_rear.png'),
        'box': require('../assets/vehicles/motor_scooter/motor_scooter_2/motor_scooter_2_box.png'),
    },
    '2_3': {
        'left': require('../assets/vehicles/motor_scooter/motor_scooter_3/motor_scooter_3_left.png'),
        'right': require('../assets/vehicles/motor_scooter/motor_scooter_3/motor_scooter_3_right.png'),
        'rear': require('../assets/vehicles/motor_scooter/motor_scooter_3/motor_scooter_3_rear.png'),
        'box': require('../assets/vehicles/motor_scooter/motor_scooter_3/motor_scooter_3_box.png'),
    },
    '2_4': {
        'left': require('../assets/vehicles/motor_scooter/motor_scooter_4/motor_scooter_4_left.png'),
        'right': require('../assets/vehicles/motor_scooter/motor_scooter_4/motor_scooter_4_right.png'),
        'rear': require('../assets/vehicles/motor_scooter/motor_scooter_4/motor_scooter_4_rear.png'),
        'box': require('../assets/vehicles/motor_scooter/motor_scooter_4/motor_scooter_4_box.png'),
    },
    '3_1': {
        'front': require('../assets/vehicles/motor_car/motor_car_1/motor_car_1_front.png'),
        'left': require('../assets/vehicles/motor_car/motor_car_1/motor_car_1_left.png'),
        'right': require('../assets/vehicles/motor_car/motor_car_1/motor_car_1_right.png'),
        'rear': require('../assets/vehicles/motor_car/motor_car_1/motor_car_1_rear.png'),
        'top': require('../assets/vehicles/motor_car/motor_car_1/motor_car_1_top.png'),
    },
    '3_2': {
        'front': require('../assets/vehicles/motor_car/motor_car_2/motor_car_2_front.png'),
        'left': require('../assets/vehicles/motor_car/motor_car_2/motor_car_2_left.png'),
        'right': require('../assets/vehicles/motor_car/motor_car_2/motor_car_2_right.png'),
        'rear': require('../assets/vehicles/motor_car/motor_car_2/motor_car_2_rear.png'),
        'top': require('../assets/vehicles/motor_car/motor_car_2/motor_car_2_top.png'),
    },
    '3_3': {
        'front': require('../assets/vehicles/motor_car/motor_car_3/motor_car_3_front.png'),
        'left': require('../assets/vehicles/motor_car/motor_car_3/motor_car_3_left.png'),
        'right': require('../assets/vehicles/motor_car/motor_car_3/motor_car_3_right.png'),
        'rear': require('../assets/vehicles/motor_car/motor_car_3/motor_car_3_rear.png'),
        'top': require('../assets/vehicles/motor_car/motor_car_3/motor_car_3_top.png'),
    },
    '3_4': {
        'front': require('../assets/vehicles/motor_car/motor_car_4/motor_car_4_front.png'),
        'left': require('../assets/vehicles/motor_car/motor_car_4/motor_car_4_left.png'),
        'right': require('../assets/vehicles/motor_car/motor_car_4/motor_car_4_right.png'),
        'rear': require('../assets/vehicles/motor_car/motor_car_4/motor_car_4_rear.png'),
        'top': require('../assets/vehicles/motor_car/motor_car_4/motor_car_4_top.png'),
    },
    '3_5': {
        'front': require('../assets/vehicles/motor_car/motor_car_5/motor_car_5_front.png'),
        'left': require('../assets/vehicles/motor_car/motor_car_5/motor_car_5_left.png'),
        'right': require('../assets/vehicles/motor_car/motor_car_5/motor_car_5_right.png'),
        'rear': require('../assets/vehicles/motor_car/motor_car_5/motor_car_5_rear.png'),
        'top': require('../assets/vehicles/motor_car/motor_car_5/motor_car_5_top.png'),
    },
    '6_1': {
        'top': require('../assets/vehicles/motor_van/motor_van_1/motor_van_1_top.png'),
        'left': require('../assets/vehicles/motor_van/motor_van_1/motor_van_1_left.png'),
        'right': require('../assets/vehicles/motor_van/motor_van_1/motor_van_1_right.png'),
        'rear': require('../assets/vehicles/motor_van/motor_van_1/motor_van_1_rear.png'),
        'front': require('../assets/vehicles/motor_van/motor_van_1/motor_van_1_front.png'),
    },
    '6_2': {
        'front': require('../assets/vehicles/motor_van/motor_van_2/motor_van_2_front.png'),
        'left': require('../assets/vehicles/motor_van/motor_van_2/motor_van_2_left.png'),
        'right': require('../assets/vehicles/motor_van/motor_van_2/motor_van_2_right.png'),
        'rear': require('../assets/vehicles/motor_van/motor_van_2/motor_van_2_rear.png'),
    },
    '6_3': {
        'front': require('../assets/vehicles/motor_van/motor_van_3/motor_van_3_front.png'),
        'left': require('../assets/vehicles/motor_van/motor_van_3/motor_van_3_left.png'),
        'right': require('../assets/vehicles/motor_van/motor_van_3/motor_van_3_right.png'),
        'rear': require('../assets/vehicles/motor_van/motor_van_3/motor_van_3_rear.png'),
        'top': require('../assets/vehicles/motor_van/motor_van_3/motor_van_3_top.png'),
    },
    '6_4': {
        'front': require('../assets/vehicles/motor_van/motor_van_4/motor_van_4_front.png'),
        'left': require('../assets/vehicles/motor_van/motor_van_4/motor_van_4_left.png'),
        'right': require('../assets/vehicles/motor_van/motor_van_4/motor_van_4_right.png'),
        'rear': require('../assets/vehicles/motor_van/motor_van_4/motor_van_4_rear.png'),
        'top': require('../assets/vehicles/motor_van/motor_van_4/motor_van_4_top.png'),
    },
    '6_5': {
        'front': require('../assets/vehicles/motor_van/motor_van_5/motor_van_5_front.png'),
        'left': require('../assets/vehicles/motor_van/motor_van_5/motor_van_5_left.png'),
        'right': require('../assets/vehicles/motor_van/motor_van_5/motor_van_5_right.png'),
        'rear': require('../assets/vehicles/motor_van/motor_van_5/motor_van_5_rear.png'),
        'top': require('../assets/vehicles/motor_van/motor_van_5/motor_van_5_top.png'),
    },
    '8_1': {
        'front': require('../assets/vehicles/bus/bus_1/bus_1_front.png'),
        'left': require('../assets/vehicles/bus/bus_1/bus_1_left.png'),
        'right': require('../assets/vehicles/bus/bus_1/bus_1_right.png'),
        'rear': require('../assets/vehicles/bus/bus_1/bus_1_rear.png'),
        'top': require('../assets/vehicles/bus/bus_1/bus_1_top.png'),
    },
    '8_2': {
        'front': require('../assets/vehicles/bus/bus_2/bus_2_front.png'),
        'left': require('../assets/vehicles/bus/bus_2/bus_2_left.png'),
        'right': require('../assets/vehicles/bus/bus_2/bus_2_right.png'),
        'rear': require('../assets/vehicles/bus/bus_2/bus_2_rear.png'),
        'top': require('../assets/vehicles/bus/bus_2/bus_2_top.png'),
    },
    '9_1': {
        'left': require('../assets/vehicles/bicycle/bicycle_1/bicycle_1_left.png'),
        'right': require('../assets/vehicles/bicycle/bicycle_1/bicycle_1_right.png'),
    },
    '9_2': {
        'left': require('../assets/vehicles/bicycle/bicycle_2/bicycle_2_left.png'),
        'right': require('../assets/vehicles/bicycle/bicycle_2/bicycle_2_right.png'),
    },
    '9_3': {
        'left': require('../assets/vehicles/bicycle/bicycle_3/bicycle_3_left.png'),
        'right': require('../assets/vehicles/bicycle/bicycle_3/bicycle_3_right.png'),
    },
    '11_1': {
        'front': require('../assets/vehicles/tricycle/tricycle_front.png'),
        'left': require('../assets/vehicles/tricycle/tricycle_left.png'),
        'right': require('../assets/vehicles/tricycle/tricycle_right.png'),
        'rear': require('../assets/vehicles/tricycle/tricycle_rear.png'),
        'top': require('../assets/vehicles/tricycle/tricycle_top.png'),
    },
    '13_1': {
        'front': require('../assets/vehicles/lorry/lorry_1/lorry_1_front.png'),
        'left': require('../assets/vehicles/lorry/lorry_1/lorry_1_left.png'),
        'right': require('../assets/vehicles/lorry/lorry_1/lorry_1_right.png'),
        'rear': require('../assets/vehicles/lorry/lorry_1/lorry_1_rear.png'),
        'top': require('../assets/vehicles/lorry/lorry_1/lorry_1_top.png'),
    },
    '13_2': {
        'front': require('../assets/vehicles/lorry/lorry_2/lorry_2_front.png'),
        'left': require('../assets/vehicles/lorry/lorry_2/lorry_2_left.png'),
        'right': require('../assets/vehicles/lorry/lorry_2/lorry_2_right.png'),
        'rear': require('../assets/vehicles/lorry/lorry_2/lorry_2_rear.png'),
        'top': require('../assets/vehicles/lorry/lorry_2/lorry_2_top.png'),
    },
    '14_1': {
        'front': require('../assets/vehicles/pick-up/pick-up_1/pick-up_1_front.png'),
        'left': require('../assets/vehicles/pick-up/pick-up_1/pick-up_1_left.png'),
        'right': require('../assets/vehicles/pick-up/pick-up_1/pick-up_1_right.png'),
        'rear': require('../assets/vehicles/pick-up/pick-up_1/pick-up_1_rear.png'),
    },
    '14_2': {
        'front': require('../assets/vehicles/pick-up/pick-up_2/pick-up_2_front.png'),
        'left': require('../assets/vehicles/pick-up/pick-up_2/pick-up_2_left.png'),
        'right': require('../assets/vehicles/pick-up/pick-up_2/pick-up_2_right.png'),
        'rear': require('../assets/vehicles/pick-up/pick-up_2/pick-up_2_rear.png'),
        'top': require('../assets/vehicles/pick-up/pick-up_2/pick-up_2_top.png'),
    },
    '15_1': {
        'front': require('../assets/vehicles/prime_mover/prime_mover_front.png'),
        'left': require('../assets/vehicles/prime_mover/prime_mover_left.png'),
        'right': require('../assets/vehicles/prime_mover/prime_mover_right.png'),
        'rear': require('../assets/vehicles/prime_mover/prime_mover_rear.png'),
        'top': require('../assets/vehicles/prime_mover/prime_mover_top.png'),
    },
    '17_1': {
        'front': require('../assets/vehicles/tipper_truck/tipper_truck_front.png'),
        'left': require('../assets/vehicles/tipper_truck/tipper_truck_left.png'),
        'right': require('../assets/vehicles/tipper_truck/tipper_truck_right.png'),
        'rear': require('../assets/vehicles/tipper_truck/tipper_truck_rear.png'),
    },
    '18_1': {
        'front': require('../assets/vehicles/tanker/tanker_front.png'),
        'left': require('../assets/vehicles/tanker/tanker_left.png'),
        'right': require('../assets/vehicles/tanker/tanker_right.png'),
        'rear': require('../assets/vehicles/tanker/tanker_rear.png'),
        'top': require('../assets/vehicles/tanker/tanker_top.png'),
    },
    '19_1': {
        'top': require('../assets/vehicles/electric_scooter/electric_scooter_1/electric_scooter_1_top.png'),
        'left': require('../assets/vehicles/electric_scooter/electric_scooter_1/electric_scooter_1_left.png'),
        'right': require('../assets/vehicles/electric_scooter/electric_scooter_1/electric_scooter_1_right.png'),
        'rear': require('../assets/vehicles/electric_scooter/electric_scooter_1/electric_scooter_1_rear.png'),
    },
    '19_2': {
        'left': require('../assets/vehicles/electric_scooter/electric_scooter_2/electric_scooter_2_left.png'),
        'right': require('../assets/vehicles/electric_scooter/electric_scooter_2/electric_scooter_2_right.png'),
    },
};