import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    Header: {
        flexDirection: "row",
        width: "100%",
        backgroundColor: "rgba(254,254,254,1)",
    },
    SpfLogo: {
        width: '33%',
        height: 50,
    },
    Banner: {
        width: '100%',
        height: 300,
    },
    HomeView: {
        flex: 1,
        alignItems: 'center',
        alignSelf: 'center',
    },
    HomeIcon: {
        width: 35,
        height: 35,
    },
    AppName: {
        marginLeft: 0,
        marginRight: 0,
        color: "rgba(0,22,62,1)",
        fontSize: 11,
        fontFamily: "ZenKakuGothicAntique-Bold",
    },
    MaskGroup: {
        marginTop: 0,
        marginLeft: 17,
        width: 30,
        height: 30,
        alignSelf: 'center',
    },
    OfficerName: {
        marginLeft: 8,
        marginRight: 8,
        color: "rgba(0,22,62,1)",
        fontSize: 11,
        fontFamily: "ZenKakuGothicAntique-Bold",
    },
    TitleBanner: {
        height: 90,
        width: '100%',
        paddingTop: 30,
        paddingBottom: 30,
        marginLeft: 10,
        backgroundColor: "rgba(254,254,254,1)",
    },
    PageTitle: {
        textAlign: 'center',
        color: "rgba(0,22,62,1)",
        fontSize: 22,
        fontFamily: "ZenKakuGothicAntique-Bold",
    },
    SummaryTitle: {
        textAlign: 'center',
        color: "rgba(0,22,62,1)",
        fontSize: 18,
        lineHeight: 20,
        fontFamily: "ZenKakuGothicAntique-Bold",
    },
    SummonsTitle: {
        margin: 20,
        alignItems: 'flex-end',
        textAlign: 'left',
        color: "rgba(0,22,62,1)",
        fontSize: 17,
        fontFamily: "ZenKakuGothicAntique-Regular",
    },
    RefNo: {
        margin: 20,
        alignItems: "flex-start",
        textAlign: "right",
        color: "rgba(0,22,62,1)",
        fontSize: 15,
        fontFamily: "ZenKakuGothicAntique-Regular",
    },
    RefId: {
        alignItems: "center",
        textAlign: 'right',
        color: "rgba(0,22,62,1)",
        fontSize: 15,
        fontFamily: "ZenKakuGothicAntique-Regular",
    },
    FlexRowCenter: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
    },
    FlexRowCenterRow: {
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
    },
    FlexRowEnd: {
        marginLeft: 40,
        marginRight: 5,
        justifyContent: "flex-end",
        flexDirection: "row",
        alignItems: "center",
        position: "flex-end",
    },
    ContainerGrey: {
        flexDirection: "column",
        justifyContent: 'center',
        alignSelf: 'center',
        width: "115%",
        height: "70%",
        backgroundColor: 'rgba(242,245,249,1)',
    },
    ContainerWhite: {
        flexDirection: "column",
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        width: '80%',
        height: '100%',
        marginTop: '15%',
        backgroundColor: "rgba(254,254,254,1)",
    },
    Label: {
        color: "rgba(0,22,62,1)",
        fontSize: 16,
        fontFamily: "ZenKakuGothicAntique-Black",
    },
    LabelNormalBold: {
        color: "rgba(0,22,62,1)",
        fontSize: 15,
        fontFamily: "ZenKakuGothicAntique-Bold",
    },
    LabelNormal: {
        color: "rgba(0,22,62,1)",
        fontSize: 15,
        lineHeight: 15,
        fontFamily: "ZenKakuGothicAntique-Regular",
    },
    LabelImpt: {
        marginRight: 12,
        color: "red",
        fontSize: 16,
        fontFamily: "ZenKakuGothicAntique-Regular"
    },
    LabelSmall: {
        marginRight: 10,
        color: "rgba(0,22,62,1)",
        fontSize: 16,
        fontFamily: "ZenKakuGothicAntique-Light"
    },
    TextContainer: {
        flex: 1,
        height: '100%',
        width: '75%',
        marginTop: '10%',
    },
    SummonsTextContainer: {
        flex: 1,
        height: '100%',
        width: '100%',
    },
    OSITextContainer: {
        flex: 1,
        height: '100%',
        width: '75%',
        marginTop: '3%',
    },
    RoundedTextInput: {
        borderWidth: 1,
        color: 'black',
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5
    },
    RoundedLongTextInput: {
        borderWidth: 1,
        height: 200,
        color: 'black',
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5
    },
    RoundedDropDownInput: {
        borderWidth: 1,
        color: 'black',
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        elevation: 5
    },
    RoundedDateInput: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        color: 'black',
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        padding: 8
    },
    TextInputContainer: {
        marginBottom: 20,
    },
    TextInputContainerSummonsVehicle: {
        marginBottom: 5,
    },
    MarginContainer: {
        height: "13%",
    },
    MarginContainerSmall: {
        height: "3%",
    },
    TabButtonContainer: {
        position: "relative",
        display: "flex",
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        width: "100%",
        borderRadius: 8,
        boxSizing: "border-box",
        backgroundColor: "rgba(254,254,254,1)",
        shadowColor: "grey",
        shadowOffset: { width: 0, height: 15 },
        shadowRadius: 10,
        shadowOpacity: 1,
        elevation: 5,
    },
    TabButton: {
        display: "flex",
        flexDirection: "row",
        flex: 3,
        justifyContent: "center",
        alignItems: "center",
        width: "33%",
        height: "100%",
        borderRadius: 8,
        boxSizing: "border-box",
    },
    TabButtonMenu: {
        color: "rgba(0,22,62,1)",
        fontSize: 15,
        lineHeight: 40,
        fontFamily: "Zen Kaku Gothic Antique, sans-serif",
        fontWeight: "400",
    },
    TabButtonHighlighted: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        width: "33%",
        height: "100%",
        borderRadius: 12,
        boxSizing: "border-box",
        backgroundColor: "rgba(9,62,160,1)",
        // text-color:"rgba(255,255,255",
    },
    TabButtonMenuHighlighted: {
        color: "rgba(254,254,254,1)",
        fontSize: 15,
        lineHeight: 40,
        fontFamily: "Zen Kaku Gothic Antique, sans-serif",
        fontWeight: "900",
    },
    OSIOfficerInfoContainer: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        width: "100%",
        marginRight: 12,
        boxSizing: "border-box",
    },
    OSIOfficerInfo: {
        marginRight: 16,
        color: "rgba(129,129,129,1)",
        fontSize: 13,
        lineHeight: 18,
        fontFamily: "Zen Kaku Gothic Antique, sans-serif",
        fontWeight: "400",
    },
    OSIPOTabContainerFrame: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        width: "100%",
        marginTop: 10,
        marginBottom: 10,
        boxSizing: "border-box",
    },
    OSIPOTabContainer: {
        alignItems: "center",
        height: "100%",
        boxSizing: "border-box",
    },
    OSIPOTabContainerHighlighted: {
        alignItems: "center",
        height: "100%",
        boxSizing: "border-box",
    },
    OSIPOTab: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        marginRight: 12,
        color: "rgba(0,22,62,1)",
        fontSize: 12,
        lineHeight: 18,
        fontFamily: "Zen Kaku Gothic Antique, sans-serif",
        fontWeight: "400",
        textAlign: "center",
    },
    OSIPOTabHighlighted: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        marginRight: 12,
        color: "rgba(9,62,160,1)",
        fontSize: 14,
        lineHeight: 18,
        fontFamily: "Zen Kaku Gothic Antique, sans-serif",
        fontWeight: "700",
        textAlign: "center",
    },
    Rectangle: {
        width: 92,
        height: 4,
        borderRadius: 8,
        backgroundColor: "rgba(254,254,254,1)",
    },
    Frame289310: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        width: "100%",
        marginRight: 42,
        boxSizing: "border-box",
    },
    Frame289312: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        width: "100%",
        boxSizing: "border-box",
    },
    SpecialZone: {
        marginRight: 16,
        color: "rgba(13,82,210,1)",
        fontSize: 16,
        lineHeight: 18,
        fontFamily: "ZenKakuGothicAntique-Regular",
    },
    Frame2893081: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        width: "100%",
    },
    FrameTopMargin: {
        marginTop: "3%",
    },
    RadioButtonContainer: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        height: "100%",
    },
    RadioButtonIcon: {
        width: 23,
        height: 23,
        marginRight: 10,
    },
    RadioButtonText: {
        color: "rgba(0,22,62,1)",
        fontSize: 11,
        lineHeight: 18,
        marginRight: 10,
        fontFamily: "Zen Kaku Gothic Antique, sans-serif",
        fontWeight: "400",
    },
    container: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        boxSizing: "border-box",
        backgroundColor: "white",
        width: '100%'
    },
    TabButtonHighlightedPedestrian: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        width: "33%",
        height: "100%",
        borderRadius: 12,
        boxSizing: "border-box",
        backgroundColor: "rgba(9,62,160,1)",
    },
    //Summons Styling
    searchIcon: {
        width:28,
        height: 28,
    },
    Frame289318: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
    width: "100%",
    height: 1120,
    paddingTop: 76,
    paddingBottom: 76,
    boxSizing: "border-box",
    },
    Frame289319: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        width: "100%",
        marginRight: 76,
        boxSizing: "border-box",
    },
    InputStyle2: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        width: "100%",
        height: 48,
        marginRight: 76,
        paddingLeft: 14,
        paddingRight: 14,
        borderWidth: 1,
        borderColor: "rgba(199,199,199,1)",
        borderRadius: 8,
        boxSizing: "border-box",
        backgroundColor: "rgba(254,254,254,1)",
    },
    SummonsSN:{
        flex :1.1,
        padding:0,
        alignItems:"center"
    
    },
    SummonsOffenderName:{
        flex :4,
        padding:3,
        alignItems:"center"
    },
    
    SummonsID:{
        flex :3,
        padding:3,
        alignItems:"center"
    },
    SummonsOffenceType:{
        flex :5,
        padding:3,
        alignItems:"center"
    },
    SummonsLocation:{
        flex :4,
        padding:3,
        alignItems:"center"
    },
    SummonsDateTime:{
        flex :3,
        padding:3,
        alignItems:"center"
    },
    SummonsSummaryList: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 15, 
        paddingHorizontal: 7,
    },
    SummonsSummaryItems: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 7,
        paddingVertical: 15, 
        backgroundColor:"white"
    },
    //Added styles for SummonsVehicle
    ContainerWhiteBG: {
        backgroundColor: "rgba(254,254,254,1)",
        width: '100%',
        flex: 1,
    },
    ContainerWhiteBGSummons: {
        backgroundColor: "rgba(254,254,254,1)",
        width: '100%',
        height: "100%",
        padding: 20,
    },
    ComponentFrame: {
        flexDirection: "column",
        justifyContent: "flex-start",
        borderRadius: 10,
        alignItems: "flex-start",
        width: "100%",
        marginRight: 42,
        boxSizing: "border-box",
    },
    VehicleInvolvedTitle: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        alignSelf: "center",
        width: "100%",
        boxSizing: "border-box",
    },
    VehicleInvolvedTitleFontStyle: {
        color: "rgba(0,22,62,1)",
        fontSize: 18,
        lineHeight: 24,
        fontFamily: "ZenKakuGothicAntique-Regular",
        fontWeight: "900",
    },
    ListContainer: {
        width: "100%",
        height: "100%",
        alignContent: "flex-start"
    },
    PedestrianContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        // justifyContent: 'flex-start',
        justifyContent: 'space-between',
        padding: 18,
        width: "100%",
    },
    SummonsListComponentFrame: {
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        width: "100%",
        marginRight: 42,
        boxSizing: "border-box",
    },
    ListComponentFrame: {
        flex: 1,
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        width: "100%",
        marginTop: 25,
        marginRight: 42,
        boxSizing: "border-box",
    },
    PassengerTitle: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        alignSelf: "center",
        width: "100%",
        boxSizing: "border-box",
    },
    MainButtonStyle3: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        height: "100%",
        paddingLeft: 14,
        paddingRight: 14,
        borderWidth: 1,
        borderColor: "rgba(9,62,160,1)",
        borderRadius: 8,
        boxSizing: "border-box",
        backgroundColor: "rgba(9,62,160,1)",
    },
    Add: {
        color: "white",
        fontSize: 14,
        marginRight: 9,
        marginBottom: 9,
        fontFamily: "ZenKakuGothicAntique-Regular",
    },
    NoItemsContainer: {
        flex:1,
        alignItems: "center",
        marginTop: "5%",
        marginBottom: "4%",
    },
    NoItemsFont: {
        // color: "#818181",
        color: "rgba(0,22,62,1)",
        fontSize: 15,
        lineHeight: 15,
        fontFamily: "ZenKakuGothicAntique-Bold",
        marginBottom: 8,
    },
    NoItemsRegularFont: {
        //color: "#818181",
        color: "rgba(0,22,62,1)",
        fontSize: 15,
        lineHeight: 15,
        fontFamily: "ZenKakuGothicAntique-Regular",
    },
    MarginContainerXSmall: {
        height: 15,
    },
    MarginContainerXLarge: {
        height: 30,
    },
    //Offence Population
    textContainerOffence: {
        flexDirection: 'row',
        justifyContent: 'space-between'
    },
    leftTextOffence: {
        flex: 1,
        textAlign: 'left'
    },
    rightTextOffence: {
        flex: 1,
        textAlign: 'right'
    },
    //Officer
    DropdownContainer: {
        flex: 1,
        alignItems: 'flex-end',
        marginEnd: 20,
    },
    Dropdown: {
        position: 'absolute',
        backgroundColor: '#fff',
        width: '24%',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
        borderRadius: 10,
    },
    CenteredView: {
        flex: 1,
        alignItems: 'flex-end',
        marginEnd: 20,
    },
    FullFrameNoPad: {
        flex: 1,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "start",
        width: "100%",
        marginLeft: 10,
    },
    FrameRowWrap: {
        flex: 2,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        width: "100%",
        marginRight: 20,
        marginTop: 5,
        boxSizing: "border-box",
        flexWrap: "wrap",
    },
    DeleteFont: {
        color: "#E74040",
        fontSize: 15,
        lineHeight: 15,
        fontFamily: "ZenKakuGothicAntique-Regular",
        marginRight: 5
    },
    EditFont: {
        color: "#00163E",
        fontSize: 15,
        lineHeight: 15,
        fontFamily: "ZenKakuGothicAntique-Regular",
        marginRight: 5
    },
})

export default styles;