import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    Header: {
        flexDirection: "row",
        width: "100%",
        backgroundColor: "rgba(254,254,254,1)",
    },
    SpfLogo: {
        width: '33%',
        height: 50,
    },
    Banner: {
        width: '100%',
        height: 300,
    },
    BannerHeight: {
        width: '100%',
        height: 100,
    },
    HomeView: {
        flex: 1,
        alignItems: 'center',
        alignSelf: 'center',
    },
    HomeIcon: {
        width: 35,
        height: 35,
    },
    AppName: {
        alignItems: "center",
        marginLeft: 0,
        marginRight: 0,
        color: "rgba(0,22,62,1)",
        fontSize: 11,
        fontFamily: "ZenKakuGothicAntique-Bold",
        lineHeight: 11
    },
    MaskGroup: {
        marginTop: 0,
        marginLeft: 17,
        width: 30,
        height: 30,
        alignSelf: 'center',
    },
    OfficerName: {
        marginLeft: 8,
        marginRight: 8,
        width: 80,
        color: "rgba(0,22,62,1)",
        fontSize: 11,
        fontFamily: "ZenKakuGothicAntique-Bold",
        lineHeight: 11
    },
    TitleBanner: {
        alignContent: "center",
        justifyContent: 'center',
        height: 60,
        width: '100%',
        paddingTop: 10,
        paddingBottom: 16,
        backgroundColor: "rgba(254,254,254,1)",
        marginTop: 3,
    },
    TitleBannerDashboard: {
        alignContent: 'center',
        justifyContent: 'center',
        height: 140,
        width: '100%',
        paddingTop: 70,
        paddingBottom: 30,
        backgroundColor: "rgba(254,254,254,1)",
    },
    WelcomeTitle: {
        textAlign: 'center',
        color: "rgba(0,22,62,1)",
        fontSize: 19,
        height: '100%',
        fontFamily: "ZenKakuGothicAntique-Regular",
        lineHeight: 19
    },
    LabelTitle: {
        textAlign: 'center',
        color: "rgba(0,22,62,1)",
        fontSize: 16,
        height: '100%',
        fontFamily: "ZenKakuGothicAntique-Regular",
        lineHeight: 16
    },
    PageTitle: {
        textAlign: 'center',
        color: "rgba(0,22,62,1)",
        fontSize: 22,
        height: '100%',
        fontFamily: "ZenKakuGothicAntique-Bold",
    },
    PageTitleLogin: {
        textAlign: 'center',
        color: "rgba(0,22,62,1)",
        fontSize: 22,
        fontFamily: "ZenKakuGothicAntique-Bold",
    },
    PageSubtitleLogin: {
        textAlign: 'center',
        color: "rgba(0,22,62,1)",
        fontSize: 20,
        fontFamily: "ZenKakuGothicAntique-Regular",
        lineHeight: 20
    },
    Placeholder: {
        color: "rgba(0,22,62,1)",
        fontSize: 14,
        fontFamily: "ZenKakuGothicAntique-Regular",
    },
    FlexRowCenter: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
    },
    FlexRowCenterRow: {
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
    },
    FlexRowEnd: {
        marginLeft: 40,
        marginRight: 5,
        justifyContent: "flex-end",
        flexDirection: "row",
        alignItems: "center",
        position: "flex-end",
    },
    ContainerGreyDeclaration: {
        flexDirection: "column",
        justifyContent: 'center',
        alignSelf: 'center',
        width: "100%",
        padding: 15,
        backgroundColor: 'rgba(242,245,249,1)',
    },
    ContainerGrey: {
        flexDirection: "column",
        justifyContent: 'center',
        alignSelf: 'center',
        width: "100%",
        height: "70%",
        backgroundColor: 'rgba(242,245,249,1)',
    },
    ContainerGreyBG: {
        backgroundColor: 'rgba(242,245,249,1)',
        height: '100%',
        width: '100%',
        borderRadius: 10, 
    },
    ContainerWhiteBG: {
        backgroundColor: "rgba(254,254,254,1)",
        width: '100%',
        flex: 1,
    },
    ContainerWhiteBGSummons: {
        backgroundColor: "rgba(254,254,254,1)",
        width: '100%',
        height:'100%',
        marginRight: 10,
        padding: 30,
    },
    WhiteBoxForVehInvolved: {
        backgroundColor: "rgba(254,254,254,1)",
        height: 150,
        width: '100%',
    },
    ContainerWhite: {
        flexDirection: "column",
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        width: '96%',
        height: '100%',
        backgroundColor: "rgba(254,254,254,1)",
    },
    ContainerWhiteBGFrame: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        backgroundColor: "rgba(254,254,254,1)",
        width: '100%',
    },
    LabelNormalBold: {
        color: "rgba(0,22,62,1)",
        fontSize: 15,
        fontFamily: "ZenKakuGothicAntique-Bold",
        padding: 2,
    },
    LabelNormal: {
        color: "rgba(0,22,62,1)",
        fontSize: 15,
        fontFamily: "ZenKakuGothicAntique-Regular",
        padding: 2,
        lineHeight: 15
    },
    LabelNormalBlue: {
        color: "rgba(13,82,210,1)",
        fontSize: 15,
        fontFamily: "ZenKakuGothicAntique-Bold",
        padding: 2,
    },
    LabelMediumBold: {
        alignItems: "flex-start",
        color: "rgba(0,22,62,1)",
        fontSize: 19,
        lineHeight: 19,
        fontFamily: "ZenKakuGothicAntique-Bold",
        padding: 2,
    },
    LabelBig: {
        alignItems: "flex-start",
        color: "rgba(0,22,62,1)",
        fontSize: 20,
        fontFamily: "ZenKakuGothicAntique-Bold",
        padding: 2,
    },
    LabelLogin: {
        color: "rgba(0,22,62,1)",
        fontSize: 18,
        fontFamily: "ZenKakuGothicAntique-Black",
    },
    Label: {
        color: "rgba(0,22,62,1)",
        fontSize: 16,
        lineHeight: 20,
        fontFamily: "ZenKakuGothicAntique-Black",
    },
    LabelWhite: {
        textAlign: "center",
        color: "rgba(254,254,254,1)",
        fontSize: 18,
        fontFamily: "ZenKakuGothicAntique-Black",
        padding: 2,
    },
    LabelWhiteMini: {
        textAlign: "center",
        color: "rgba(254,254,254,1)",
        fontSize: 16,
        fontFamily: "ZenKakuGothicAntique-Black",
        padding: 2,
    },
    LabelWhiteSmall: {
        textAlign: "center",
        color: "rgba(254,254,254,1)",
        fontSize: 16,
        fontFamily: "ZenKakuGothicAntique-Light",
        padding: 2,
    },
    LabelWhiteTiny: {
        textAlign: "center",
        color: "rgba(254,254,254,1)",
        fontSize: 14,
        fontFamily: "ZenKakuGothicAntique-Light",
        paddingTop: 8,
        lineHeight: 14,
    },
    LabelImpt: {
        marginRight: 12,
        color: "red",
        fontSize: 16,
        fontFamily: "ZenKakuGothicAntique-Regular"
    },
    LabelImptSmall: {
        marginRight: 12,
        color: "red",
        fontSize: 14,
        fontFamily: "ZenKakuGothicAntique-Regular"
    },
    LabelThin: {
        marginRight: 10,
        color: "rgba(0,22,62,1)",
        fontSize: 16,
        fontFamily: "ZenKakuGothicAntique-Light"
    },
    //Testing
    LabelThinDescription: {
        marginRight: 10,
        color: "rgba(0,22,62,1)",
        fontSize: 16,
        fontWeight: '100',
        fontFamily: "ZenKakuGothicAntique-Light",
    },
    LabelSmall: {
        alignItems: "flex-start",
        color: "rgba(0,22,62,1)",
        fontSize: 14,
        lineHeight: 14,
        fontFamily: "ZenKakuGothicAntique-Black",
        padding: 2,
    },
    LabelSmaller: {
        alignItems: "flex-start",
        color: "rgba(0,22,62,1)",
        fontSize: 14,
        fontFamily: "ZenKakuGothicAntique-Black",
        padding: 2,
    },
    TextContainer: {
        flex: 1,
        height: '100%',
        width: '75%',
        marginTop: '10%',
    },
    OSITextContainer: {
        flex: 1,
        height: '100%',
        width: '89%',
        marginTop: '3%',
    },
    SummonsTextContainer: {
        flex: 1,
        height: '100%',
        width: '95%',
        marginTop: '3%',
    },
    RoundedTextInput: {
        borderWidth: 1,
        color: 'black',
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        padding: 20,
        height: 56,
    },
    DropdownRoundedTextInputFont: {
        borderWidth: 1,
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        height: 56,
        width: "100%",
        backgroundColor: 'white',
        color: "rgba(0,22,62,1)",
        fontSize: 14,
        fontFamily: "ZenKakuGothicAntique-Regular",
        padding: 10
    },
    RoundedTextInputFont: {
        borderWidth: 1,
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        height: 56,
        color: "rgba(0,22,62,1)",
        fontSize: 14,
        fontFamily: "ZenKakuGothicAntique-Regular",
        padding: 15
    },
    RoundedTextInputWhiteLogin: {
        borderWidth: 1,
        color: 'black',
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        width:"100%", 
        backgroundColor: "white",
        height: 67,
    },
    RoundedTextInputWhite: {
        borderWidth: 1,
        color: 'black',
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        width:"100%", 
        backgroundColor: "white",
        height: 56,
    },
    DateTextInputWhiteFont: {
        flex: 1, 
        paddingVertical: 6, 
        paddingHorizontal: 12, 
        color: "rgba(0,22,62,1)",
        fontSize: 14,
        fontFamily: "ZenKakuGothicAntique-Regular",
    },
    RoundedTextInputWhiteFont: {
        borderWidth: 1,
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        width:"100%", 
        backgroundColor: "white",
        height: 56,
        color: "rgba(0,22,62,1)",
        fontSize: 14,
        fontFamily: "ZenKakuGothicAntique-Regular",
        padding: 15
    },
    RoundedTextInputVDRWhiteFont: {
        borderWidth: 1,
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        width:"100%", 
        backgroundColor: "white",
        height: 50,
        color: "rgba(0,22,62,1)",
        fontSize: 14,
        fontFamily: "ZenKakuGothicAntique-Regular",
        padding: 15
    },
    RoundedTextInputVDRWhite: {
        borderWidth: 1,
        color: 'black',
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        width:"100%", 
        backgroundColor: "white",
        height: 50,
    },
    RoundedLongTextInput: {
        borderWidth: 1,
        height: 200,
        color: 'black',
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5
    },
    RoundedLongTextInputMediumWhite: {
        borderWidth: 1,
        textAlignVertical: "top",
        height: 100,
        color: 'black',
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        backgroundColor: "white",
    },
    RoundedLongTextInputMediumWhiteFont: {
        borderWidth: 1,
        textAlignVertical: "top",
        height: 100,
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        backgroundColor: "white",
        color: "rgba(0,22,62,1)",
        fontSize: 14,
        fontFamily: "ZenKakuGothicAntique-Regular",
        padding: 10
    },
    RoundedLongTextInputWhiteFont: {
        borderWidth: 1,
        textAlignVertical: "top",
        height: 180,
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        backgroundColor: "white",
        color: "rgba(0,22,62,1)",
        fontSize: 14,
        fontFamily: "ZenKakuGothicAntique-Regular",
        padding: 10
    },
    RoundedLongTextInputMediumLongWhite: {
        borderWidth: 1,
        textAlignVertical: "top",
        height: 150,
        color: 'black',
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        backgroundColor: "white",
    },
    RoundedLongTextInputWhite: {
        borderWidth: 1,
        textAlignVertical: "top",
        height: 180,
        color: 'black',
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        backgroundColor: "white",
    },
    RoundedDropDownInput: {
        borderWidth: 1,
        color: 'black',
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        elevation: 5,
        height: 53,
    },
    RoundedDateInputNoHeightLimit: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        color: 'black',
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        paddingRight: 8,
        minHeight: 53
    },
    RoundedDateInput: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        color: 'black',
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        paddingRight: 8,
        height: 53,
    },
    RoundedDateInputWhite: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        color: 'black',
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        padding: 8,
        height: 53,
        backgroundColor: "white",
    },
    RoundedDateInputVDRWhite: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        color: 'black',
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        padding: 8,
        height: 45,
        backgroundColor: "white",
    },
    TextInputContainer: {
        marginBottom: 10,
        width: "100%"
    },
    TextInputContainerHalf: {
        marginBottom: 10,
        width: "50%",
        padding: 8,
    },
    PedestrianContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        // justifyContent: 'flex-start',
        justifyContent: 'space-between',
        padding: 18,
        width: "100%",
    },
    PedestrianContainerWhite: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        // justifyContent: 'flex-start',
        justifyContent: 'space-between',
        padding: 18,
        width: "100%",
        backgroundColor: 'white'
    },
    PedestrianContainerLessPad: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 5,
        width: "100%",
    },
    MarginContainerXSmall: {
        height: 15,
    },
    MarginContainerSmall: {
        height: "3%",
    },
    MarginContainerMedium: {
        height: "7%",
    },
    MarginContainer: {
        height: "13%",
    },
    TabButtonContainer: {
        position: "relative",
        display: "flex",
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        width: "100%",
        borderRadius: 8,
        boxSizing: "border-box",
        backgroundColor: "rgba(254,254,254,1)",
        shadowColor: "grey",
        shadowOffset: { width: 0, height: 15 },
        shadowRadius: 10,
        shadowOpacity: 1,
        elevation: 5,
    },
    TabButton: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        width: "33%",
        height: "100%",
        borderRadius: 8,
        boxSizing: "border-box",
    },
    TabButtonMenu: {
        color: "rgba(0,22,62,1)",
        fontSize: 15,
        lineHeight: 40,
        fontFamily: "ZenKakuGothicAntique-Regular",
        fontWeight: "400",
    },
    TabButtonHighlighted: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        width: "33%",
        height: "100%",
        borderRadius: 8,
        boxSizing: "border-box",
        backgroundColor: "rgba(9,62,160,1)",
    },
    TabButtonMenuHighlighted: {
        color: "rgba(254,254,254,1)",
        fontSize: 15,
        lineHeight: 40,
        fontFamily: "ZenKakuGothicAntique-Regular",
        fontWeight: "900",
    },
    OSIOfficerInfoContainer: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        width: "100%",
        marginRight: 12,
        boxSizing: "border-box",
    },
    OSIOfficerInfo: {
        marginRight: 16,
        color: "rgba(129,129,129,1)",
        fontSize: 13,
        lineHeight: 18,
        fontFamily: "ZenKakuGothicAntique-Regular",
        fontWeight: "400",
    },
    OSIPOSmallerTabContainerFrame: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        alignSelf: "center",
        width: "80%",
        marginTop: 10,
        boxSizing: "border-box",
    },
    SketchContainerFrame: {
        display: "flex",
        flex: 1,
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        width: "100%",
        boxSizing: "border-box",
    },
    OSIPOTabContainerFrameNew: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        width: "100%",
        boxSizing: "border-box",
    },
    OSIPOTabContainerFrame: {
        display: "flex",
        flex: 1,
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        width: "100%",
        height: "100%",
        boxSizing: "border-box",
    },
    OSIPOTabContainer: {
        alignItems: "center",
        height: "100%",
        boxSizing: "border-box",
    },
    OSIPOTabContainerHighlighted: {
        alignItems: "center",
        height: "100%",
        boxSizing: "border-box",
    },
    OSIPOTab: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        marginRight: 12,
        color: "rgba(0,22,62,1)",
        fontSize: 12,
        lineHeight: 18,
        fontFamily: "ZenKakuGothicAntique-Regular",
        fontWeight: "400",
        textAlign: "center",
    },
    OSIPOTabHighlighted: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        marginRight: 12,
        color: "rgba(9,62,160,1)",
        fontSize: 14,
        lineHeight: 18,
        fontFamily: "ZenKakuGothicAntique-Regular",
        fontWeight: "700",
        textAlign: "center",
    },
    Rectangle: {
        width: 92,
        height: 4,
        borderRadius: 8,
        backgroundColor: "rgba(254,254,254,1)",
    },
    HorizontalComponentFrame: {
        flex: 1,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        width: "30%",
        height: "100%",
        marginTop: 25,
        boxSizing: "border-box",
    },
    ListComponentFrame: {
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        width: "100%",
        marginTop: 25,
        marginRight: 42,
        boxSizing: "border-box",
    },
    ComponentFrame: {
        flexDirection: "column",
        justifyContent: "flex-start",
        borderRadius: 10,
        alignItems: "flex-start",
        width: "100%",
        marginRight: 42,
        boxSizing: "border-box",
    },
    FrameVDR: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        width: "100%",
    },
    Frame289312: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        width: "100%",
        boxSizing: "border-box",
    },
    SpecialZone: {
        marginRight: 16,
        color: "rgba(13,82,210,1)",
        fontSize: 16,
        lineHeight: 18,
        fontFamily: "ZenKakuGothicAntique-Regular",
        fontWeight: "700",
    },
    Frame2893081: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        width: "100%",
        boxSizing: "border-box",
    },
    LoginFrameTopMargin: {
        marginTop: "3%",
        width:"100%",
        height: "100%"
    },
    FrameTopMargin: {
        marginTop: "3%",
        width:"100%",
    },
    RadioButtonContainerFlex: {
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center", 
        marginBottom: 8, 
    },
    RadioButtonContainer: {
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        height: "100%",
    },
    RadioButtonIcon: {
        width: 23,
        height: 23,
        marginRight: 10,
    },
    RadioButtonTextTight: {
        color: "rgba(0,22,62,1)",
        fontSize: 13,
        lineHeight: 18,
        fontFamily: "ZenKakuGothicAntique-Regular",
        fontWeight: "400",
    },
    RadioButtonText: {
        color: "rgba(0,22,62,1)",
        fontSize: 14,
        lineHeight: 18,
        marginRight: 7,
        fontFamily: "ZenKakuGothicAntique-Regular",
        fontWeight: "400",
    },
    VehicleInvolvedTitle: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        alignSelf: "center",
        width: "100%",
        boxSizing: "border-box",
    },
    VehicleInvolvedTitleFontStyle: {
        textAlign:"center",
        color: "rgba(0,22,62,1)",
        fontSize: 18,
        lineHeight: 24,
        fontFamily: "ZenKakuGothicAntique-Regular",
        fontWeight: "900",
    },
    CaptionFrame: {
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        width: "100%",
        padding: 5,
        boxSizing: "border-box",
    },
    DashboardCaptionFrame: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        width: "100%",
        boxSizing: "border-box",
    },  
    CategoryFont: {
        color: "rgba(0,22,62,1)",
        borderBottomColor: 'rgba(154,154,154,1)',
        borderBottomWidth: 1,
        fontFamily: "ZenKakuGothicAntique-Light",
        fontSize: 18,
        lineHeight: 18,
        width: "60%",
        alignSelf: 'center',
        paddingTop: 10
    },
    VehicleRegistrationNoFrame: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        width: "100%",
        padding: 6,
        boxSizing: "border-box",
    },
    DeclarationFont: {
        marginRight: 16,
        color: "rgba(129,129,129,1)",
        fontSize: 15,
        lineHeight: 18,
        textAlign:'justify',
        fontFamily: "ZenKakuGothicAntique-Bold",
    },
    VehicleRegistrationNoFont: {
        marginRight: 16,
        color: "#292929",
        fontSize: 15,
        lineHeight: 18,
        fontFamily: "ZenKakuGothicAntique-Regular",
        fontWeight: "400",
        alignSelf: "center",
    },
    CaptionFont: {
        marginRight: 16,
        color: "rgba(129,129,129,1)",
        fontSize: 15,
        lineHeight: 18,
        fontFamily: "ZenKakuGothicAntique-Regular",
        fontWeight: "400",
        alignSelf: "center",
    },
    VehicleInformationContainer: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "flex-start",
        width: "100%",
        marginRight: 20,
        boxSizing: "border-box",
    },
    Frame289327: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        width: "100%",
        height: 86,
        marginRight: 20,
        boxSizing: "border-box",
    },
    VehicleInformation: {
        marginRight: 8,
        color: "rgba(13,82,210,1)",
        fontSize: 15,
        lineHeight: 18,
        fontFamily: "ZenKakuGothicAntique-Bold",
    },
    RegistrationNo: {
        marginRight: 12,
        color: "rgba(0,22,62,1)",
        fontSize: 15,
        lineHeight: 18,
        fontFamily: "ZenKakuGothicAntique-Regular",
        fontWeight: "700",
    },
    FullFrameDeclaration: {
        flex: 1,
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "start",
        width: "100%",
        padding: 10,
        marginTop: 5,
        boxSizing: "border-box",
    },
    FullFrameVDR: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "start",
        width: "100%",
        padding: 5,
        boxSizing: "border-box",
    },
    FullFrame: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "start",
        width: "100%",
        padding: 10,
        boxSizing: "border-box",
    },
    FullFrameRowCenter: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        width: "100%",
        padding: 10,
        boxSizing: "border-box",
    },
    FullFrameFlexNoPad: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "start",
        width: "100%",
        paddingHorizontal: 10,
        boxSizing: "border-box",
    },
    FullFrameNoPad: {
        flex: 1,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "start",
        width: "100%",
        marginLeft: 10,
    },
    FullFrameRow: {
        flex: 1,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "start",
        width: "100%",
        padding: 10,
        marginTop: 5,
        boxSizing: "border-box",
    },
    OffenceFrameRow: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        padding: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#ccc',
    },
    FrameRowNew: {
        flex: 1,
        display: "flex",
        flexDirection: "row",
        padding: 10,
    },
    FrameRow: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        width: "100%",
        marginRight: 20,
        boxSizing: "border-box",
    },
    FrameRowDeclaration: {
        flex: 2,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        width: "100%",
        marginRight: 20,
        marginTop: 5,
        boxSizing: "border-box",
    },
    FrameRowWrap: {
        flex: 2,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        width: "100%",
        marginRight: 20,
        marginTop: 5,
        boxSizing: "border-box",
        flexWrap: "wrap",
    },
    RadioFrameRowWrap: {
        flexDirection: "row",
        justifyContent: "flex-start",
        width: "100%",
        marginTop: 8
    },
    HalfFrameContainerVDR: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        width: "50%",
        height: "100%",
        padding: 5,
        boxSizing: "border-box",
    },
    OffenceThirdFrameContainer: {
        flex: 0.5,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        padding: 15,
        boxSizing: "border-box",
    },
    OffenceThirdFrameContainerEnd: {
        flex: 0.5,
        flexDirection: "row",
        justifyContent: "flex-end",
        alignItems: "center",
        padding: 15,
        boxSizing: "border-box",
    },
    ThirdFrameContainer: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        width: "33%",
        height: "100%",
        padding: 8,
        boxSizing: "border-box",
    },
    HalfFrameContainer: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        width: "50%",
        height: "100%",
        padding: 8,
        boxSizing: "border-box",
    },
    HalfFrameContainerRow: {
        flex: 1,
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "flex-start",
        width: "50%",
        padding: 8,
    },
    HalfContainer: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        width: "50%",
        height: "100%",
        boxSizing: "border-box",
    },
    OffenceDescContainer: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        width: "83%",
        height: "100%",
        padding: 8,
        boxSizing: "border-box",
    },
    OffenceActionsContainer: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "flex-end",
        alignItems: "center",
        width: "17%",
        height: "100%",
        padding: 8,
        boxSizing: "border-box",
    },
    VehicleType: {
        marginRight: 12,
        color: "rgba(0,22,62,1)",
        fontSize: 18,
        lineHeight: 18,
        fontFamily: "ZenKakuGothicAntique-Regular",
        fontWeight: "700",
    },
    Select: {
        marginRight: 16,
        color: "rgba(129,129,129,1)",
        fontSize: 18,
        lineHeight: 18,
        fontFamily: "ZenKakuGothicAntique-Regular",
        fontWeight: "400",
    },
    Icons: {
        width: 16,
        height: 16,
    },
    AccordionHeader: {
        marginRight: 8,
        color: "rgba(13,82,210,1)",
        fontSize: 17,
        lineHeight: 17,
        fontFamily: "ZenKakuGothicAntique-Bold",
    },
    SubAccordionHeader: {
        marginRight: 8,
        color: "rgba(13,82,210,1)",
        fontSize: 16,
        lineHeight: 16,
        fontFamily: "ZenKakuGothicAntique-Bold",
    },
    AccordionFrame: {
        justifyContent: "space-between",
        alignItems: "start",
        alignSelf: "start",
        width: "100%",
        marginTop: 8,
        marginBottom: 8,
        boxSizing: "border-box",
    },
    AccordionIcon: {
        alignItems: "end",
        alignSelf: "end",
    },
    AgeFrame: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        width: "100%",
        height: "100%",
        boxSizing: "border-box",
    },
    AgeFont: {
        color: "rgba(0,22,62,1)",
        fontSize: 15,
        lineHeight: 15,
        fontFamily: "ZenKakuGothicAntique-Regular",
    },
    PassengerTitle: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        alignSelf: "center",
        width: "100%",
        boxSizing: "border-box",
    },
    MainButtonStyle3: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        height: "100%",
        paddingLeft: 14,
        paddingRight: 14,
        borderWidth: 1,
        borderColor: "rgba(9,62,160,1)",
        borderRadius: 8,
        boxSizing: "border-box",
        backgroundColor: "rgba(9,62,160,1)",
    },
    Add: {
        color: "white",
        fontSize: 14,
        marginRight: 9,
        marginBottom: 9,
        fontFamily: "ZenKakuGothicAntique-Regular",
    },
    DeclarationFrame: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "center",
        width: "100%",
        boxSizing: "border-box",
    },
    Frame289429: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "flex-start",
        width: "100%",
        marginRight: 56,
        boxSizing: "border-box",
    },
    PedestrianItem: {
        flexDirection: "column",
        justifyContent: "flex-start",
        width: "100%",
    },
    ListContainer: {
        width: "100%",
        height: "100%",
        alignContent: "flex-start"
    },
    BlueBox: {
        backgroundColor: "rgba(9,62,160,1)",
        width: 180,
        height: 170,
        alignContent: 'center',
        justifyContent: "center",
        padding: 8,
        margin: 10,
        borderRadius: 13
    },
    TestViewContainer: {
        flex:1,
        height: '100%',
        width:'100%',
    },
    NoItemsContainer: {
        flex:1,
        alignItems: "center",
        marginTop: "5%",
        marginBottom: "4%",
    },
    NoItemsFont: {
        //color: "#818181",
        color: "rgba(0,22,62,1)",
        fontSize: 15,
        lineHeight: 15,
        fontFamily: "ZenKakuGothicAntique-Bold",
        marginBottom: 8,
    },
    NoItemsRegularFont: {
        //color: "#818181",
        color: "rgba(0,22,62,1)",
        fontSize: 15,
        lineHeight: 15,
        fontFamily: "ZenKakuGothicAntique-Regular",
    },
    PhotoUploadFrame: {
        flexDirection: "row",
        justifyContent: "center",
        width: "100%",
        height: "20%",
        marginTop: 25,
        boxSizing: "border-box",
    },
    VdrListFrame: {
        flexDirection: "row",
        justifyContent: "center",
        width: "100%",
        height: "72%",
        marginTop: 25,
        boxSizing: "border-box",
    },
    PhotoUploadListFrame: {
        flexDirection: "row",
        justifyContent: "center",
        width: "100%",
        height: "71%",
        marginTop: 25,
        boxSizing: "border-box",
    },
    SketchListFrame: {
        flexDirection: "row",
        justifyContent: "center",
        width: "100%",
        height: "66%",
        marginTop: 25,
        boxSizing: "border-box",
    },
    SketchFrame: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        width: 200, 
        height: 200, 
        marginRight: 10,
        borderWidth: 1,
        borderColor: "rgba(199,199,199,1)",
        borderRadius: 8,
        backgroundColor: "rgba(254,254,254,1)",
    },
    TakePhotoFrame: {
        display: "flex",
        borderStyle: 'dashed',
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        width: 195, 
        height: 195, 
        marginRight: 10,
        marginLeft: 10,
        borderWidth: 1,
        borderColor: "rgba(199,199,199,1)",
        borderRadius: 8,
        backgroundColor: "rgba(254,254,254,1)",
    },
    PhotoFrame: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        width: 195, 
        height: 195, 
        marginRight: 10,
        borderWidth: 1,
        borderColor: "rgba(199,199,199,1)",
        borderRadius: 8,
        backgroundColor: "rgba(254,254,254,1)",
        borderStyle: 'dashed',
        position: 'relative',
    },
    DeleteIcon: {
        position: 'absolute',
        bottom: 15,
        right: 15,
        backgroundColor: 'rgba(255, 255, 255, 0.6)',
        borderRadius: 30,
        padding: 9,
    },
    RtaLocation: {
        color: "rgba(0,22,62,1)",
        marginTop: 9,
        fontSize: 15,
        lineHeight: 15,
        fontFamily: "ZenKakuGothicAntique-Regular",
    },
    CaptionInput: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        backgroundColor: 'white',
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        padding: 8,
    },
    RoundedCaptionInputOld: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        backgroundColor: 'white',
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        padding: 8,
        height: 50
    },
    RoundedCaptionInput: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 7,
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderWidth: 1,
        borderColor: '#C7C7C7',
        borderRadius: 8,
        width: 190, 
        height: 45,
    },
    VdrRoundedCaptionInputFont: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 7,
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderWidth: 1,
        borderColor: '#C7C7C7',
        borderRadius: 8,
        width: 214, 
        height: 45,
        color: "rgba(0,22,62,1)",
        fontSize: 14,
        fontFamily: "ZenKakuGothicAntique-Regular",
        padding: 10
    },
    RoundedCaptionInputFont: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 7,
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderWidth: 1,
        borderColor: '#C7C7C7',
        borderRadius: 8,
        width: 190, 
        height: 45,
        color: "rgba(0,22,62,1)",
        fontSize: 14,
        lineHeight: 14,
        fontFamily: "ZenKakuGothicAntique-Regular",
        padding: 10
    },
    RoundedCaptionDottedInput: {
        flexDirection: "row",
        alignItems: "center",
        width: "100%",
        height: 48,
        paddingLeft: 14,
        paddingRight: 14,
        borderWidth: 1,
        borderColor: "rgba(199,199,199,1)",
        borderRadius: 8,
        boxSizing: "border-box",
        backgroundColor: "rgba(254,254,254,1)",
    },
    VdrTakePhotoFrame: {
        display: "flex",
        borderStyle: 'dashed',
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        width: 205, 
        height: 195, 
        marginRight: 10,
        marginLeft: 10,
        borderWidth: 1,
        borderColor: "rgba(199,199,199,1)",
        borderRadius: 8,
        backgroundColor: "rgba(254,254,254,1)",
    },
    VdrPhotoFrame: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        width: 215, 
        height: 195, 
        marginRight: 10,
        borderWidth: 1,
        borderColor: "rgba(199,199,199,1)",
        borderRadius: 8,
        backgroundColor: "rgba(254,254,254,1)",
        borderStyle: 'dashed',
        position: 'relative',
    },
    VdrPhoto: {
        width: 205, 
        height: 205,
        borderRadius: 8,
    },
    Photo: {
        width: 180, 
        height: 180, 
        borderRadius: 8,
    },
    PhotoList: {
        justifyContent: 'flex-start',
    },
    PhotoItem: {
        flex: 1,
        width: 170, 
        margin: 5,
    },
    PedestrianFont: {
        color: "#818181",
        fontSize: 15,
        lineHeight: 15,
        fontFamily: "ZenKakuGothicAntique-Bold",
    },
    DeleteFont: {
        color: "#E74040",
        fontSize: 15,
        lineHeight: 15,
        fontFamily: "ZenKakuGothicAntique-Regular",
        marginRight: 5
    },
    EditFont: {
        color: "#00163E",
        fontSize: 15,
        lineHeight: 15,
        fontFamily: "ZenKakuGothicAntique-Regular",
        marginRight: 5
    },
    ViewFont: {
        color: "#00163E",
        fontSize: 15,
        lineHeight: 15,
        fontFamily: "ZenKakuGothicAntique-Regular",
    },
    HorizontalVector: {
        borderBottomColor: '#D4D4D4',
        borderBottomWidth: StyleSheet.hairlineWidth,
        marginBottom: 8,
        marginTop: 5,
    },
    ModalHorizontalVector: {
        borderBottomColor: '#D4D4D4',
        borderBottomWidth: StyleSheet.hairlineWidth,
        width: "70%"
    },
    VerticalVector: {
        borderRightColor: '#292929',
        borderRightWidth: StyleSheet.hairlineWidth,
        height: "79%",
    },
    TextInputWrapper: {
        position: 'relative',
    },
    CharCounter: {
        position: 'absolute',
        bottom: 10,
        right: 10,
        fontSize: 12,
        color: '#818181',
    },
    SketchDashedFrame: {
        borderWidth: 2,
        borderColor: '#C7C7C7',
        borderStyle: 'dashed',
        alignItems: 'center',
        justifyContent: 'center',
        height: 200,
        width: 200,
        padding: 10,
        margin: 10,
        borderRadius: 10, // Optional, if you want rounded corners
    },
    SketchComponent: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        width: "100%",
        boxSizing: "border-box",
    },
    CenteredView: {
        flex: 1,
        direction: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    ModalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    ModalContent: {
        backgroundColor: 'white',
        padding: 20,
        borderRadius: 5,
    },
    ModalView: {
        backgroundColor: 'white',
        alignItems: 'center',
        width: "45%",
        height: 400,
        borderRadius: 8,
    },
    ModalTextInputContainer: {
        marginBottom: 10,
        width: "70%",
        height: "100%",
    },
    ModalRoundedTextInput: {
        borderWidth: 1,
        color: 'black',
        borderColor: '#C7C7C7',
        borderRadius: 5,
        marginTop: 5,
        padding: 20,
        height: 55,
    },
    ButtonContainer: {
        flexDirection: 'column',
        justifyContent: 'center',
        width: '80%',
        marginTop: 20,
        position: 'absolute',
        bottom: 20,
    },
    SketchBanner: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        width: "100%",
        height: 70,
        paddingLeft: 56,
        paddingRight: 56,
        paddingTop: 16,
        paddingBottom: 16,
        boxSizing: "border-box",
        backgroundColor: "rgba(254,254,254,1)",
    },
    SketchBannerTitle: {
        marginRight: 63,
        color: "rgba(0,22,62,1)",
        fontSize: 22,
        lineHeight: 36,
        fontFamily: "ZenKakuGothicAntique-Bold",
    },
    SketchBannerText: {
        color: "rgba(129,129,129,1)",
        fontSize: 16,
        lineHeight: 18,
        fontFamily: "ZenKakuGothicAntique-Regular",
    },
    SketchBannerTextComponent: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "flex-end",
        alignItems: "center",
        height: "100%",
        boxSizing: "border-box",
    },
    SketchBannerTextComponentMargin: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "flex-end",
        alignItems: "center",
        height: "100%",
        boxSizing: "border-box",
        marginRight: 35,
    },
    ModalImageContainer: {
        flex: 1,
        justifyContent: 'center',
    },
    VDRModalView: {
        backgroundColor: 'white',
        alignItems: 'center',
        width: "80%",
        height: "72%",
        borderRadius: 8,
    },
    VDRImageViewContainer: {
        width: "100%",
        height: "100%",
        alignItems: "center",
        justifyContent: 'center',
        backgroundColor: 'white'
    },
    VDRImageView: {
        width: 300,
        height: 300,
        resizeMode: 'contain',
    },
    DropdownContainer: {
        flex: 1,
        alignItems: 'flex-end',
        marginEnd: 20,
    },
    Dropdown: {
        position: 'absolute',
        backgroundColor: '#fff',
        width: '24%',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
        borderRadius: 10,
    },
    OffenceAlignLeft: {

    },
    SummonsSN:{
        flex :2
    },
    SummonsOffenderName:{
        flex :4
    },
    SummonsID:{
        flex :3
    },
    SummonsOffenceType:{
        flex :5
    },
    SummonsLocation:{
        flex :4
    },
    SummonsDateTime:{
        flex :3
    },
    SummonsTitleContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        boxSizing: "border-box",
        backgroundColor: "white",
        width: '100%'
    },
    SummonsTitle: {
        margin: 20,
        alignItems: 'flex-end',
        textAlign: 'left',
        color: "rgba(0,22,62,1)",
        fontSize: 17,
        fontFamily: "ZenKakuGothicAntique-Regular",
    },
    RefNo: {
        margin: 20,
        alignItems: "flex-start",
        textAlign: "right",
        color: "rgba(0,22,62,1)",
        fontSize: 15,
        fontFamily: "ZenKakuGothicAntique-Regular",
    },
     RefId: {
        alignItems: "center",
        textAlign: 'right',
        color: "rgba(0,22,62,1)",
        fontSize: 15,
        fontFamily: "ZenKakuGothicAntique-Regular",
    },
    SummonsSummaryList: {
        flexDirection: "row",
        alignItems: "center",
        padding:10,
    },
    SummonsSummaryItems: {
        flexDirection: "row",
        alignItems: "center",
        margin:5,
        padding:5,
        backgroundColor:"white"
    }, 
    container: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        boxSizing: "border-box",
        backgroundColor: "white",
        width: '100%'
    },
    MarginContainerX: {
        height: 30,
    },
    MarginContainerXLarge: {
        height: 50,
    },
    //Offence Population
    textContainerOffence: {
        flexDirection: 'row',
        justifyContent: 'space-between'
    },
    leftTextOffence: {
        flex: 1,
        textAlign: 'left'
    },
    rightTextOffence: {
        flex: 1,
        textAlign: 'right'
    },
})

export default styles;